import assert from 'node:assert/strict';
import test from 'node:test';
import {
  allocateImportedAssetPath,
  formatAssetImportSummary,
  normalizeAssetImportFolder,
  sanitizeImportedAssetName,
  validateImportedAssetName,
} from '../src/assetImportModel.ts';

test('asset import targets stay inside the selected Assets folder', () => {
  assert.equal(normalizeAssetImportFolder('Assets\\Sprites\\UI'), 'Assets/Sprites/UI');
  assert.throws(() => normalizeAssetImportFolder('../Outside'), /under Assets/);
  assert.throws(() => normalizeAssetImportFolder('Assets/../Outside'), /under Assets/);
});

test('asset import sanitizes file names and rejects generated or unsupported files', () => {
  assert.equal(sanitizeImportedAssetName('C:\\Downloads\\Hero:Idle.png'), 'Hero_Idle.png');
  assert.equal(sanitizeImportedAssetName('CON.png'), '_CON.png');
  assert.match(sanitizeImportedAssetName(`${'a'.repeat(220)}.png`), /\.png$/);
  assert.equal(sanitizeImportedAssetName(`${'a'.repeat(220)}.png`).length, 180);
  assert.equal(validateImportedAssetName('Character.glb'), 'Character.glb');
  assert.equal(validateImportedAssetName('Upper Body.mavatar'), 'Upper Body.mavatar');
  assert.equal(validateImportedAssetName('Wet Paint.minst'), 'Wet Paint.minst');
  assert.throws(() => validateImportedAssetName('Hero.sprite.json'), /generated by MEngine/);
  assert.throws(() => validateImportedAssetName('setup.exe'), /unsupported asset type/);
});

test('asset import never overwrites and allocates case-insensitive numeric suffixes', () => {
  const occupied = new Set([
    'Assets/Sprites/Hero.png',
    'Assets/Sprites/Hero 1.png',
    'Assets/Sprites/RUN.MANIM',
  ]);
  assert.equal(
    allocateImportedAssetPath('Assets/Sprites', 'hero.png', occupied),
    'Assets/Sprites/hero 2.png',
  );
  assert.equal(
    allocateImportedAssetPath('Assets/Sprites', 'Run.manim', occupied),
    'Assets/Sprites/Run 1.manim',
  );
  assert.equal(
    allocateImportedAssetPath('Assets/Sprites', 'new.sprite.png', occupied),
    'Assets/Sprites/new.sprite.png',
  );
});

test('asset import summaries expose partial failures instead of hiding them', () => {
  assert.equal(
    formatAssetImportSummary({ imported: ['Assets/UI/Button.png'], rejected: [] }, 'Assets/UI'),
    'Imported Assets/UI/Button.png',
  );
  assert.match(
    formatAssetImportSummary({
      imported: ['Assets/UI/Button.png'],
      rejected: [{ name: 'tool.exe', reason: 'unsupported asset type' }],
    }, 'Assets/UI'),
    /Skipped 1: tool\.exe: unsupported asset type/,
  );
  assert.match(
    formatAssetImportSummary({
      imported: [],
      rejected: [{ name: 'tool.exe', reason: 'unsupported asset type' }],
    }, 'Assets/UI'),
    /^No assets were imported\. Skipped 1:/,
  );
});
