use crate::parse::{Def, DefKind, Field};
use heck::ToPascalCase;

pub fn emit_rust(defs: &[Def]) -> String {
    let mut out = String::new();
    out.push_str("//! AUTO-GENERATED by mengine-idl. Do not edit by hand.\n");
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("use crate::component::Component;\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    for def in defs.iter().filter(|d| matches!(d.kind, DefKind::Component)) {
        out.push_str(&emit_rust_component(def));
        out.push('\n');
    }

    out.push_str("pub mod meta {\n");
    out.push_str("    pub const COMPONENT_NAMES: &[&str] = &[\n");
    for def in defs.iter().filter(|d| matches!(d.kind, DefKind::Component)) {
        out.push_str(&format!("        \"{}\",\n", def.name));
    }
    out.push_str("    ];\n}\n");
    out
}

fn emit_rust_component(def: &Def) -> String {
    let mut out = String::new();
    let derive = if def.fields.is_empty() {
        "#[derive(Clone, Debug, Default, Serialize, Deserialize)]\n"
    } else {
        "#[derive(Clone, Debug, Serialize, Deserialize)]\n"
    };
    out.push_str(derive);
    out.push_str(&format!("pub struct {} {{\n", def.name));
    for f in &def.fields {
        let rust_ty = map_rust_type(&f.ty, f.optional);
        out.push_str(&format!("    pub {}: {},\n", f.name, rust_ty));
    }
    out.push_str("}\n\n");

    if !def.fields.is_empty() {
        out.push_str(&format!("impl Default for {} {{\n", def.name));
        out.push_str("    fn default() -> Self {\n        Self {\n");
        for f in &def.fields {
            let d = default_expr(&f.ty, f.default.as_deref(), f.optional);
            out.push_str(&format!("            {}: {},\n", f.name, d));
        }
        out.push_str("        }\n    }\n}\n\n");
    }

    out.push_str(&format!("impl Component for {} {{\n", def.name));
    out.push_str(&format!(
        "    fn type_name() -> &'static str {{ \"{}\" }}\n",
        def.name
    ));
    out.push_str("}\n");
    out
}

fn map_rust_type(ty: &str, optional: bool) -> String {
    let base = match ty {
        "string" => "String".into(),
        "bool" => "bool".into(),
        "int" => "i32".into(),
        "u64" => "u64".into(),
        "float" => "f32".into(),
        "float2" => "[f32; 2]".into(),
        "float3" => "[f32; 3]".into(),
        "float4" => "[f32; 4]".into(),
        "object" => "serde_json::Value".into(),
        other => other.to_pascal_case(),
    };
    if optional {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn default_expr(ty: &str, default: Option<&str>, optional: bool) -> String {
    if optional {
        return "None".into();
    }
    if let Some(d) = default {
        return match ty {
            "string" => {
                let s = d.trim().trim_matches('"');
                format!("\"{s}\".into()")
            }
            "bool" => d.to_string(),
            "int" | "u64" | "float" => {
                if ty == "float" && !d.contains('.') {
                    format!("{d}.0")
                } else {
                    d.to_string()
                }
            }
            "float2" | "float3" | "float4" => array_lit(d),
            _ => "Default::default()".into(),
        };
    }
    match ty {
        "string" => "String::new()".into(),
        "bool" => "false".into(),
        "int" => "0".into(),
        "u64" => "0".into(),
        "float" => "0.0".into(),
        "float2" => "[0.0, 0.0]".into(),
        "float3" => "[0.0, 0.0, 0.0]".into(),
        "float4" => "[0.0, 0.0, 0.0, 0.0]".into(),
        "object" => "serde_json::Value::Null".into(),
        _ => "Default::default()".into(),
    }
}

fn array_lit(d: &str) -> String {
    let inner = d.trim().trim_start_matches('[').trim_end_matches(']');
    let parts: Vec<String> = inner
        .split(',')
        .map(|p| {
            let p = p.trim();
            if p.contains('.') {
                p.to_string()
            } else {
                format!("{p}.0")
            }
        })
        .collect();
    format!("[{}]", parts.join(", "))
}

pub fn emit_typescript(defs: &[Def]) -> String {
    let mut out = String::new();
    out.push_str("/** AUTO-GENERATED by mengine-idl. Do not edit by hand. */\n\n");

    for def in defs.iter().filter(|d| matches!(d.kind, DefKind::Component)) {
        out.push_str(&format!("export interface {} {{\n", def.name));
        for f in &def.fields {
            let opt = if f.optional { "?" } else { "" };
            out.push_str(&format!(
                "  {}{}: {};\n",
                camel(&f.name),
                opt,
                map_ts_type(&f.ty)
            ));
        }
        out.push_str("}\n\n");
    }

    out.push_str("export type ComponentName =\n");
    let names: Vec<_> = defs
        .iter()
        .filter(|d| matches!(d.kind, DefKind::Component))
        .map(|d| format!("  | '{}'", d.name))
        .collect();
    if names.is_empty() {
        out.push_str("  | never;\n");
    } else {
        out.push_str(&names.join("\n"));
        out.push_str(";\n\n");
    }

    out.push_str("export const COMPONENT_NAMES = [\n");
    for def in defs.iter().filter(|d| matches!(d.kind, DefKind::Component)) {
        out.push_str(&format!("  '{}',\n", def.name));
    }
    out.push_str("] as const;\n\n");

    out.push_str("export type WorldCommand =\n");
    for def in defs.iter().filter(|d| matches!(d.kind, DefKind::Command)) {
        out.push_str(&format!("  | {{ op: '{}'", camel_cmd(&def.name)));
        for f in &def.fields {
            let ty = map_ts_type(&f.ty);
            if f.optional {
                out.push_str(&format!("; {}?: {}", camel(&f.name), ty));
            } else {
                out.push_str(&format!("; {}: {}", camel(&f.name), ty));
            }
        }
        out.push_str(" }\n");
    }
    out.push_str(";\n");
    out
}

fn camel(s: &str) -> String {
    let mut parts = s.split('_');
    let first = parts.next().unwrap_or("").to_string();
    let rest: String = parts
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect();
    // keep IDL field names as-is if already camel / snake mixed — prefer as written for TS
    if s.contains('_') {
        first + &rest
    } else {
        s.to_string()
    }
}

fn camel_cmd(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

fn map_ts_type(ty: &str) -> &'static str {
    match ty {
        "string" => "string",
        "bool" => "boolean",
        "int" | "u64" => "number",
        "float" => "number",
        "float2" => "[number, number]",
        "float3" => "[number, number, number]",
        "float4" => "[number, number, number, number]",
        "object" => "Record<string, unknown>",
        _ => "unknown",
    }
}

pub fn emit_json_schema(defs: &[Def]) -> String {
    let mut schemas = serde_json::Map::new();
    for def in defs {
        let mut props = serde_json::Map::new();
        let mut required = Vec::new();
        for f in &def.fields {
            props.insert(f.name.clone(), json_type(&f.ty));
            if !f.optional {
                required.push(serde_json::Value::String(f.name.clone()));
            }
        }
        let mut obj = serde_json::Map::new();
        obj.insert("type".into(), serde_json::Value::String("object".into()));
        obj.insert("properties".into(), serde_json::Value::Object(props));
        if !required.is_empty() {
            obj.insert("required".into(), serde_json::Value::Array(required));
        }
        schemas.insert(def.name.clone(), serde_json::Value::Object(obj));
    }
    serde_json::to_string_pretty(&schemas).unwrap_or_else(|_| "{}".into())
}

fn json_type(ty: &str) -> serde_json::Value {
    let mut m = serde_json::Map::new();
    match ty {
        "string" => {
            m.insert("type".into(), "string".into());
        }
        "bool" => {
            m.insert("type".into(), "boolean".into());
        }
        "int" | "u64" | "float" => {
            m.insert("type".into(), "number".into());
        }
        "float2" | "float3" | "float4" => {
            m.insert("type".into(), "array".into());
            m.insert("items".into(), serde_json::json!({ "type": "number" }));
        }
        "object" => {
            m.insert("type".into(), "object".into());
        }
        _ => {
            m.insert("type".into(), "object".into());
        }
    }
    serde_json::Value::Object(m)
}

#[allow(dead_code)]
fn _field_doc(f: &Field) -> String {
    format!("{}: {}", f.name, f.ty)
}
