export const TYPED_ENTITY_KINDS = [
  'empty',
  'cube',
  'camera',
  'camera2d',
  'sprite',
  'animated_sprite',
  'line2d',
  'grid',
  'tilemap',
  'spine_skeleton',
  'particle_3d',
  'particle_2d',
  'directional_light',
  'point_light',
  'spot_light',
  'environment_light',
  'global_light_2d',
  'point_light_2d',
  'audio_source',
  'audio_listener',
  'audio_mixer',
  'ui_canvas',
  'ui_image',
  'ui_raw_image',
  'ui_button',
  'ui_text',
  'ui_toggle',
  'ui_slider',
  'ui_scrollbar',
  'ui_progress_bar',
  'ui_input_field',
  'ui_dropdown',
  'ui_list_view',
  'ui_scroll_view',
  'ui_tab_view',
  'ui_panel',
  'ui_layout_group',
] as const;

export type TypedEntityKind = (typeof TYPED_ENTITY_KINDS)[number];
