export const ASSET_IMPORT_MAX_BYTES = 64 * 1024 * 1024;
export const ASSET_IMPORT_ACCEPT = [
  '.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.tga', '.tif', '.tiff', '.hdr', '.exr',
  '.wav', '.ogg', '.mp3', '.flac',
  '.gltf', '.glb',
  '.atlas', '.skel', '.json',
  '.mmat', '.mat', '.mshader', '.prefab', '.matlas', '.manim', '.mcontroller', '.mavatar', '.mtimeline',
].join(',');

const SUPPORTED_EXTENSIONS = new Set(ASSET_IMPORT_ACCEPT.split(','));

export type ImportableAssetFile = {
  name: string;
  size: number;
  arrayBuffer: () => Promise<ArrayBuffer>;
};

export type AssetImportRejection = {
  name: string;
  reason: string;
};

export type AssetImportResult = {
  imported: string[];
  rejected: AssetImportRejection[];
};

export function normalizeAssetImportFolder(raw: string): string {
  let value = String(raw ?? '').trim().replace(/\\/g, '/').replace(/^\/+/, '');
  if (value.toLowerCase().startsWith('assets/')) value = `Assets/${value.slice('assets/'.length)}`;
  if (value.toLowerCase() === 'assets') value = 'Assets';
  const segments = value.split('/').filter(Boolean);
  if (segments[0] !== 'Assets' || segments.some((segment) => segment === '..' || segment === '.')) {
    throw new Error(`asset path must be under Assets: ${raw}`);
  }
  return segments.join('/');
}

export function sanitizeImportedAssetName(raw: string): string {
  const leaf = String(raw ?? '').replace(/\\/g, '/').split('/').pop()?.trim() ?? '';
  let sanitized = leaf
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, '_')
    .replace(/[. ]+$/g, '');
  if (!sanitized || sanitized === '.' || sanitized === '..') {
    throw new Error('asset file name is empty');
  }
  const dot = sanitized.lastIndexOf('.');
  const extension = dot > 0 ? sanitized.slice(dot) : '';
  if (sanitized.length > 180) {
    sanitized = `${sanitized.slice(0, Math.max(1, 180 - extension.length))}${extension}`;
  }
  const stem = (extension ? sanitized.slice(0, -extension.length) : sanitized).toUpperCase();
  if (/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/.test(stem)) sanitized = `_${sanitized}`;
  return sanitized;
}

function assetExtension(name: string): string {
  const lower = name.toLowerCase();
  const extension = [...SUPPORTED_EXTENSIONS]
    .sort((a, b) => b.length - a.length)
    .find((candidate) => lower.endsWith(candidate));
  return extension ?? '';
}

export function validateImportedAssetName(name: string): string {
  const sanitized = sanitizeImportedAssetName(name);
  if (sanitized.toLowerCase().endsWith('.sprite.json')) {
    throw new Error('sprite import sidecars are generated by MEngine');
  }
  if (!assetExtension(sanitized)) {
    throw new Error('unsupported asset type');
  }
  return sanitized;
}

function splitAssetStem(name: string): { stem: string; extension: string } {
  const extension = assetExtension(name);
  return {
    stem: extension ? name.slice(0, -extension.length) : name,
    extension,
  };
}

export function allocateImportedAssetPath(
  targetFolder: string,
  fileName: string,
  occupiedPaths: ReadonlySet<string>,
): string {
  const folder = normalizeAssetImportFolder(targetFolder);
  const normalizedName = validateImportedAssetName(fileName);
  const occupied = new Set([...occupiedPaths].map((value) => value.toLowerCase()));
  const { stem, extension } = splitAssetStem(normalizedName);
  let suffix = 0;
  while (true) {
    const candidateName = suffix === 0 ? normalizedName : `${stem} ${suffix}${extension}`;
    const candidate = `${folder}/${candidateName}`;
    if (!occupied.has(candidate.toLowerCase())) return candidate;
    suffix += 1;
  }
}

export function formatAssetImportSummary(result: AssetImportResult, targetFolder: string): string {
  if (result.imported.length === 0 && result.rejected.length === 0) return '';
  const imported = result.imported.length === 0
    ? 'No assets were imported'
    : result.imported.length === 1
    ? `Imported ${result.imported[0]}`
    : `Imported ${result.imported.length} assets into ${normalizeAssetImportFolder(targetFolder)}`;
  if (result.rejected.length === 0) return imported;
  const rejected = result.rejected.map((item) => `${item.name}: ${item.reason}`).join('; ');
  return `${imported}. Skipped ${result.rejected.length}: ${rejected}`;
}
