/** Interactive tile painting for the official Unity tile samples. Generated by import-unity-tiles.py. */
type PaintCell = { x: number; y: number; tile: number };
const paintCells = new Map<string, PaintCell>();
const paintUndo: PaintCell[][] = [];
let selectedTile = 0;
let controlsVisible = true;
const cellKey = (x: number, y: number): string => `${x},${y}`;
const cellName = (x: number, y: number): string => `Tile ${x} ${y}`;
const terrainMasks = [0, 1, 5, 7, 17, 21, 23, 29, 31, 85, 87, 95, 119, 127, 255];
type NeighborRule = { neighbors: number[]; positions: number[][]; rotate: boolean; sprite: string };

function neighborMatches(condition: number, tileIndex: number, otherIndex: number | undefined): boolean {
  if (condition === 0) return true;
  const tile = tileData.tiles[tileIndex], other = otherIndex === undefined ? undefined : tileData.tiles[otherIndex];
  if (tile.family === 'sibling' && (condition === 1 || condition === 2)) {
    const same = other?.family === 'sibling' && tile.group === other.group;
    return condition === 1 ? same : !same;
  }
  if (tile.family === 'terrain' && (condition === 3 || condition === 4)) return other?.family === 'terrain' && (condition === 3 ? tile.group === other.group : tile.group !== other.group);
  if (tile.family === 'type') {
    if (condition === 3) return other?.family === 'type';
    if (condition === 2) return other?.family !== 'type';
  }
  return condition === 1 ? tileIndex === otherIndex : condition === 2 && tileIndex !== otherIndex;
}

function onSceneLoaded(): void {
  paintCells.clear(); paintUndo.length = 0; selectedTile = 0; controlsVisible = true;
  for (const cell of tileData.cells) paintCells.set(cellKey(cell.x, cell.y), { ...cell });
}

function tileVisual(cell: PaintCell): { sprite: string; rotation: number[] } {
  const tile = tileData.tiles[cell.tile];
  let index = 0, turns = 0;
  if (tileData.kind === 'custom' || tileData.kind === 'override') {
    if (!tile.family) {
      const original = tileData.cells.find(value => value.x === cell.x && value.y === cell.y && value.tile === cell.tile);
      return { sprite: tile.defaultSprite, rotation: original?.rotation ?? [0, 0, 0, 1] };
    }
    for (const rule of tile.rules as NeighborRule[]) for (let turn = 0; turn < (rule.rotate ? 4 : 1); turn++) {
      if (rule.neighbors.every((condition, index) => {
        let [x, y] = rule.positions[index];
        for (let i = 0; i < turn; i++) [x, y] = [y, -x];
        return neighborMatches(condition, cell.tile, paintCells.get(cellKey(cell.x + x, cell.y + y))?.tile);
      })) {
        const angle = -turn * Math.PI / 2;
        return { sprite: rule.sprite, rotation: [0, 0, Math.sin(angle / 2), Math.cos(angle / 2)] };
      }
    }
    return { sprite: tile.defaultSprite, rotation: [0, 0, 0, 1] };
  }
  if (tileData.kind === 'auto') {
    let mask = 0;
    for (let y = -1; y <= 1; y++) for (let x = -1; x <= 1; x++) if (paintCells.get(cellKey(cell.x + x, cell.y + y))?.tile === cell.tile) mask |= 1 << ((y + 1) * 3 + x + 1);
    for (const [diagonal, sides] of [[1,10],[4,34],[64,136],[256,160]]) if ((mask & sides) !== sides) mask &= ~diagonal;
    return { sprite: (tile.lookup as Record<string, string>)[String(mask)] ?? tile.defaultSprite, rotation: [0, 0, 0, 1] };
  }
  if (tileData.kind === 'terrain' || tileData.kind === 'pipeline') {
    const offsets = tileData.kind === 'terrain' ? [[0,1],[1,1],[1,0],[1,-1],[0,-1],[-1,-1],[-1,0],[-1,1]] : [[0,1],[1,0],[0,-1],[-1,0]];
    let mask = 0;
    offsets.forEach(([x, y], bit) => { if (paintCells.get(cellKey(cell.x + x, cell.y + y))?.tile === cell.tile) mask |= 1 << bit; });
    if (tileData.kind === 'terrain') {
      for (const [diagonal, sides] of [[2,5],[8,20],[32,80],[128,65]]) if ((mask & sides) !== sides) mask &= ~diagonal;
      outer: for (let i = 0; i < terrainMasks.length; i++) for (let turn = 0; turn < 4; turn++) {
        const rotated = ((terrainMasks[i] << (2 * turn)) | (terrainMasks[i] >>> (8 - 2 * turn))) & 255;
        if (rotated === mask) { index = i; turns = turn; break outer; }
      }
    } else {
      index = [0,2,2,1,2,2,1,3,2,1,2,3,1,3,3,4][mask];
      turns = [0,0,1,2,0,0,3,1,1,1,1,0,0,3,2,0][mask];
    }
  } else {
    const original = tileData.cells.find(value => value.x === cell.x && value.y === cell.y && value.tile === cell.tile);
    if (original) return { sprite: original.sprite, rotation: original.rotation };
    // Reproducible per-cell weighted sampling; weights include duplicate uniform entries.
    let hash = Math.imul(cell.x ^ 0x9e3779b9, 0x85ebca6b) ^ Math.imul(cell.y, 0xc2b2ae35);
    hash = Math.imul(hash ^ (hash >>> 16), 0x85ebca6b);
    hash = Math.imul(hash ^ (hash >>> 13), 0xc2b2ae35);
    let choice = ((hash ^ (hash >>> 16)) >>> 0) / 4294967296 * tile.weights.reduce((sum, weight) => sum + weight, 0);
    index = tile.weights.length - 1;
    for (let i = 0; i < tile.weights.length; i++) { choice -= tile.weights[i]; if (choice < 0) { index = i; break; } }
  }
  const angle = -turns * Math.PI / 2;
  return { sprite: tile.sprites[index], rotation: [0, 0, Math.sin(angle / 2), Math.cos(angle / 2)] };
}

function refreshPaint(): void {
  const entities = new Map(engine.snapshot.entities.filter(entity => entity.name?.startsWith('Tile ')).map(entity => [entity.name, entity]));
  for (const cell of paintCells.values()) {
    const name = cellName(cell.x, cell.y), entity = entities.get(name), visual = tileVisual(cell);
    const transform = { position: [cell.x + 0.5, cell.y + 0.5, 0], rotation: visual.rotation, scale: [1, 1, 1] };
    if (!entity) engine.pushCommandJson(JSON.stringify({ op: 'spawn', name, components: { Transform: transform, SpriteRenderer: { sprite: visual.sprite, color: tileData.tiles[cell.tile].color, size: [1, 1] } } }));
    else {
      if (entity.components.SpriteRenderer.sprite !== visual.sprite) engine.pushCommandJson(JSON.stringify({ op: 'setComponent', entity: entity.entity, component: 'SpriteRenderer', value: { ...entity.components.SpriteRenderer, sprite: visual.sprite } }));
      if (Math.abs(entity.components.Transform.rotation.reduce((sum: number, value: number, i: number) => sum + value * visual.rotation[i], 0)) < 0.999999) engine.pushCommandJson(JSON.stringify({ op: 'setComponent', entity: entity.entity, component: 'Transform', value: transform }));
      entities.delete(name);
    }
  }
  for (const entity of entities.values()) engine.pushCommandJson(JSON.stringify({ op: 'despawn', entity: entity.entity }));
}

function onTick(): void {
  const input = engine.input;
  if (input.pressedKeys.includes('KeyR')) { engine.reloadScene(); return; }
  if (input.pressedKeys.includes('KeyH')) {
    controlsVisible = !controlsVisible;
    const label = engine.snapshot.entities.find(entity => entity.name === 'Brush Controls');
    if (label) engine.pushCommandJson(JSON.stringify({ op: 'setComponent', entity: label.entity, component: 'Text', value: { ...label.components.Text, enabled: controlsVisible } }));
  }
  for (let i = 0; i < tileData.tiles.length; i++) if (input.pressedKeys.includes(`Digit${i + 1}`)) {
    selectedTile = i;
    const label = engine.snapshot.entities.find(entity => entity.name === 'Brush Controls');
    const choices = tileData.tiles.map((_, index) => index + 1).join(' / ');
    if (label) engine.pushCommandJson(JSON.stringify({ op: 'setComponent', entity: label.entity, component: 'Text', value: { ...label.components.Text, enabled: controlsVisible, text: `${tileData.title}\n${tileData.tiles[i].name}\n\nLeft mouse: paint\nRight mouse: erase\n${tileData.tiles.length > 1 ? choices + ': choose tile\n' : ''}Z: undo    R: reset\nH: show / hide controls` } }));
  }
  if (input.pressedKeys.includes('KeyZ') && paintUndo.length) {
    paintCells.clear();
    for (const cell of paintUndo.pop()!) paintCells.set(cellKey(cell.x, cell.y), cell);
    refreshPaint(); return;
  }
  if (!input.buttons.includes(0) && !input.buttons.includes(2)) return;
  const [width, height] = input.viewport, [px, py] = input.pointer;
  if (width <= 0 || height <= 0 || px < 0 || py < 0 || px >= width || py >= height || (controlsVisible && px < 241 * width / 960 && py < 270 * width / 960)) return;
  const x = Math.floor((px / width - 0.5) * tileData.cameraSize * 2 * width / height + tileData.cameraPosition[0]);
  const y = Math.floor((0.5 - py / height) * tileData.cameraSize * 2 + tileData.cameraPosition[1]);
  const key = cellKey(x, y), erase = input.buttons.includes(2);
  if (erase ? !paintCells.has(key) : paintCells.get(key)?.tile === selectedTile) return;
  paintUndo.push([...paintCells.values()].map(cell => ({ ...cell })));
  if (paintUndo.length > 64) paintUndo.shift();
  if (erase) paintCells.delete(key); else paintCells.set(key, { x, y, tile: selectedTile });
  refreshPaint();
}
